---
output: pdf_document
header-includes: 
- \usepackage[utf8]{inputenc}
- \usepackage[T1]{fontenc}
- \usepackage[ngerman]{babel}
- \usepackage{amsmath,amssymb,amsthm}
- \usepackage{dsfont}
- \usepackage{listings}
- \usepackage{floatrow}
- \usepackage{fancyhdr}
- \pagestyle{fancy}
- '\fancyhead[C,C]{Gruppe 5: Robin Baudisch, Merlin Kopfmann, Maximilian Neudert}'
- \fancyhead[L]{}
- \fancyhead[R]{}
- \fancyfoot[C,C]{\thepage}
- \renewcommand{\footrulewidth}{0.4pt}
---

<style type="text/css">
body{
  font-size: 12px;
}
h1 {
  font-size: 18px;
}
h1 {
  font-size: 14px;
}
h1 {
  font-size: 12px;
}
</style>

```{r global_options, include=FALSE}
knitr::opts_chunk$set(error=TRUE,        # Keep compiling upon error
                      collapse=TRUE,     # collapse by default
                      echo=TRUE,         # echo code by default
                      comment = "#>",    # change comment character
                      fig.width = 10,     # set figure width
                      out.width = "100%", # set width of displayed images
                      warning=TRUE,      # show R warnings
                      message=FALSE)     # show R messages
```

<!---** Hochschule Darmstadt | Studiengang Data Science | Sommersemester 2019 **--->


# Aufgabe 1
### a)
```{r}
load('awards.RData')
load('DebTrivedi.RData')

plm = glm(
  num_awards ~ prog + math,
  data = awards,
  family= poisson
)

lambda_voc <- predict.glm(plm, data.frame(prog = "Vocational", math = 60), type="response")
lambda_acd <- predict.glm(plm, data.frame(prog = "Academic", math = 60), type="response")
lambda_gen <- predict.glm(plm, data.frame(prog = "General", math = 60), type="response")

1- sum(dpois(0:2, lambda_gen))
1- sum(dpois(0:2, lambda_voc))
1- sum(dpois(0:2, lambda_acd))
```

### b)
```{r}
library("lmtest")

plm_without = glm(
  num_awards ~ math,
  data = awards,
  family= poisson
)

lmtest::lrtest(plm_without, plm)
AIC(plm_without, plm)
``` 